### ISSUE TITLE
데이터 시각화 기능을 통계 기능으로 변환

### ISSUE THREAD

**Issue by jak010** [jak010/MNU_CAPSTONE#10]
피드백 중 "데이터에 대한 통계치를 나타내는 기능 필요"를 반영하여 기존 데이터 시각화에서 "메모리 사용량 평균", "훈련 데이터 갯수" 를 나타내는 등 통계기능으로 바꿉니다.

**Comment by bluetoonist** [comment]
commit  in : 1671a74f061df31c352281e0ad4f16441f6779d0
